#!/usr/bin/env python3
# HADESx Decoder  -  https://github.com/N6RFM/HADESx-Decoder
# Authors: N6RFM, with Claude (an AI assistant made by Anthropic).
# Licence: MIT (see LICENSE).
"""Build a single-file decoder (dist/hadesx_standalone.py) = core + folder output + voice + IQ reader + front end + cli.

    python3 tools/build_standalone.py
    python3 dist/hadesx_standalone.py recording.wav --outdir ~/hades-sa --voice-wav voice.wav
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'src', 'hadesx')
ORDER = ['core', 'genesis', 'layout', 'voice', 'iqfile', 'frontend', 'cli']
TITLES = {'genesis': "per-type folder output (port of AMSAT-EA's HADES-SA decoder)", 'layout': 'one folder per satellite', 'voice': 'voice', 'iqfile': 'IQ files (raw and WAV)',
          'frontend': 'signal chain', 'cli': 'command line'}


def read(name):
    return open(os.path.join(SRC, name + '.py')).read()


def strip_module(text, name):
    """Remove the module docstring and turn every intra-package import into `pass` (the names are all in one namespace now)."""
    if name != 'core':
        text = re.sub(r'\A(?:#[^\n]*\n)+', '', text)                    # the credit block (the file starts with the core's once)
        text = re.sub(r'^"""[\s\S]*?"""\n', '', text, count=1)
    text = re.sub(r'^([ \t]*)from \.\w+ import (?:\([^)]*\)|[^\n]*)\n', r'\1pass\n', text, flags=re.M)
    return text


def build(path):
    parts = {n: strip_module(read(n), n) for n in ORDER}
    # voice's command line entry would clash with cli.main
    parts['voice'] = parts['voice'].replace('def main(argv=None):', 'def voice_main(argv=None):')
    parts['voice'] = parts['voice'].replace("if __name__ == '__main__':\n    main()\n", '')
    out = ['#!/usr/bin/env python3\n'
           '# HADESx Decoder  -  https://github.com/N6RFM/HADESx-Decoder  -  single-file build, generated by tools/build_standalone.py\n'
           '# Authors: N6RFM, with Claude (an AI assistant made by Anthropic).  Licence: MIT.\n'
           "# Built on AMSAT-EA's open documentation and source code (CC BY 4.0) and the SSDV format of Philip Heron: see NOTICE.md.\n"
           '"""UNNE-1B / HADES-SA / HADES-L decoder - single-file build of the hadesx package.\n'
           'Usage: python3 hadesx_standalone.py recording.wav [--fs 50000] [--outdir DIR] [--dll hadesr.dll] '
           '[--voice-wav out.wav] [--log frames.jsonl]\n"""\n', parts['core']]
    for n in ORDER[1:]:
        out.append('\n\n# ===== %s =====\n' % TITLES[n])
        out.append(parts[n])
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, 'w').write(''.join(out))
    os.chmod(path, 0o755)
    return path


def main():
    print('wrote', build(os.path.join(ROOT, 'dist', 'hadesx_standalone.py')))


if __name__ == '__main__':
    main()
